postgres:
  build: database
  environment:
    - POSTGRES_USER=diaspora
    - POSTGRES_PASSWORD=diaspora
    - POSTGRES_DB=diaspora_production
    - PGDATA=/var/lib/postgresql/data/pgdata
  volumes:
    - ../data/postgres:/var/cache/postgres
  privileged: true

redis:
  build: redis
  command: redis-server --appendonly yes

diaspora:
  build: diaspora
  links:
    - postgres
    - redis
  volumes:
    - ../data/diaspora:/home/diaspora
  expose:
    - "3000"
  working_dir: /home/diaspora
  privileged: true
